### ISSUE TITLE
Error in the Prop of method getDevices()

### ISSUE THREAD

**Issue by MefAldemisov** [aigenseer/qr-scanner-redirect#10]
Hello. I faced with error during plugin's attempt to get camera's permissions:
```js
TypeError: Cannot read property 'enumerateDevices' of undefined
    at videoStream.tsx:29
    at new Promise (<anonymous>)
    at t.default.getDevices (videoStream.tsx:28)
    at p.initStream (dialogcamera.component.tsx:136)
    at p.componentWillMount (dialogcamera.component.tsx:75)
    at fn (react-dom.production.min.js:135)
    at Lu (react-dom.production.min.js:167)
    at ju (react-dom.production.min.js:180)
    at Gr (react-dom.production.min.js:232)
    at Zr (react-dom.production.min.js:233)
```
[Here is error-producing file](https://github.com/aigenseer/qr-scanner-redirect/blob/master/qr-scanner-js-src/src/lib/videoStream.tsx)

I have tried similar code in the browser:
```js
navigator.mediaDevices.enumerateDevices().then((list) =>{
        let devices = list.filter(e => e.kind === 'videoinput').sort((a, b) => {
          if(a.label.includes('back') && b.label.includes('front')){
            return -1
          }else if(a.label.includes('front') && b.label.includes('back')){
            return 1
          }
          return 0;
        });
        console.log(devices);
      }).catch(reject);
```

And required array was printed... Why is it so and how to fix this issue?

Probably, the recompilation (building) will solve that issue.

**Comment by aigenseer** [comment]
Hello @MefAldemisov,

Wish browser do you use?

**Comment by MefAldemisov** [comment]
Tested with google chrome (latest version), Safari and some chromium-based browser.

**Comment by aigenseer** [comment]
Have you got a https connection ? Or only with http? The latest browser only support the camera api with a https connection.

**Comment by MefAldemisov** [comment]
I've tested many solutions of similar problem and usually tools with http(s) limitations work with http on localhost.

**Comment by aigenseer** [comment]
Hallo @MefAldemisov,

I updated the plugin to the version 1.0.4. Please can you test it with your device.

**Comment by MefAldemisov** [comment]
@aigenseer  Thank you!!! It works!
