### ISSUE TITLE
how can you change the image of the little scanner? 

### ISSUE THREAD

**Issue by nicksarro123** [aigenseer/qr-scanner-redirect#19]
how can you change the image of the little scanner?

**Comment by aigenseer** [comment]
halllo @nicksarro123, 

no, that was not intended in the development. Alternatively, I can offer you the following solution.

1.) Add the plugin using a shortcut.
2) Add the following code to your CSS file to hide the element.
3) Create your own button with your desired image.
4) Add the following attributes to your button / HTML tag: onclick="window.qrscannerredirect.open ()"

Example:

CSS:
`
#qrscannerredirect
{
display: none
}
`

HTML:
`
<button onclick = "window.qrscannerredirect.open ()"> Open scanner </button>
`
