### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by DoronYosha** [aigenseer/qr-scanner-redirect#2]
Hello
I installed and activate the plugin, than I used the shortcode:  ['qr-scanner-redirect']
But nothing has happened...

**Comment by mbk87234** [comment]
remove the apostrophe ' ' marks enclosing qr-scanner-redirect. there should be only square brackets only. it will work then

**Comment by sunjaypb123** [comment]
> remove the apostrophe ' ' marks enclosing qr-scanner-redirect. there should be only square brackets only. it will work then

hello sir i tried but not working pls help

**Comment by sunjaypb123** [comment]
> Hello
> I installed and activate the plugin, than I used the shortcode: ['qr-scanner-redirect']
> But nothing has happened...

hello sir is that working for u ??

**Comment by DoronYosha** [comment]
Hi
I just tried it now and It seems to be working,
Thanks!!
Doron

**Comment by mbk87234** [comment]
`[qr-scanner-redirect]
`
use this

**Comment by aigenseer** [comment]
Hallo @DoronYosha,

I update the discription. The @mbk87234 ' s statement is correct.
