### ISSUE TITLE
Save settings doesnt work well - Force redirect

### ISSUE THREAD

**Issue by skyhighmedia** [aigenseer/qr-scanner-redirect#23]
Hi Viktor,

I've been testing the plugin you made and came across some issues. 

Save setting
In the WP backend when i change the settings, fill in some translations and hit save everything works. But when i go back to the QR scanner settings page everything is reset to default, so no checkboxes checked and English text.

Force redirect
Doesn't work well as you can test yourself with the info below:
Page with the scanner: https://skyhighweb.nl/martinus/
QR code: https://skyhighweb.nl/martinus/qr/
If you scan the code without force redirect it works fine, you get the pop-up, but with force redirect on it doesn't redirect well. In my mobile browser (Chrome) you can see the browser loading (blue bar top left) but it doesn't automatically redirects. But when i move the camera away from the QR code the scanner immediately redirects to the right page.

WordPress 5.7.1, Hello Theme. Disabling other plugins doesnt make a difference.

Would be nice if you can help me out, cause apart from these issues the plugin seems to work great!

If you need anymore info, let me know. Thanks in advance!

Roel Beekmans
info@skyhighmedia.nl

**Comment by fgrweb** [comment]
Same here.  The plugins works fine, but soesn't save the settings.
Any solution?

**Comment by aigenseer** [comment]
Hallo, I fixed the problem with saving the settings with the new version.

**Comment by rodeista** [comment]
> Hallo, I fixed the problem with saving the settings with the new version.

Still same problem here (last version of plugin) - not possible to save language settings. And also starting scanner with class "qr-scanner-redirect-open" looks like it does not work :(
