### ISSUE TITLE
Closing Div Missing in metaboxes.php

### ISSUE THREAD

**Issue by donalalong** [aigenseer/qr-scanner-redirect#29]
Hi,

I found that your plugin was causing the Divi page builder to be displayed in the sidebar instead of the main page/post editing area and it looks like the cause is a missing closing div in the metaboxes.php file.

I've taken some screenshots and added them to the shared folder below for you to see what I mean...

[Dropbox Link Here](https://www.dropbox.com/sh/23w04d8n1bcidl2/AABf15FcFA6e-Cwwq0mXDTJta?dl=0)

https://www.dropbox.com/sh/23w04d8n1bcidl2/AABf15FcFA6e-Cwwq0mXDTJta?dl=0

Best Regards,
Donal
WP Cork

**Comment by aigenseer** [comment]
Hallo @donalalong, Thank you for your comment. I removed the closing div.
