### ISSUE TITLE
Camera extremly "zoomed" on Android

### ISSUE THREAD

**Issue by rodeista** [aigenseer/qr-scanner-redirect#30]
Hello, If I open your QR reader, camera is extremly zoomed (looks like 1:1 resolution of my camera) so it can not focus (it can, but only for QR code cca 1 meter away from my camera -> it is imposible to read QR code for example in a book). Can you help me with that please?
Thanks a lot
Tom

PS: On Android, Huawei P30 Pro

**Comment by rodeista** [comment]
Update - I know where is the problem - my phone has 4 cameras and your script use the zoom one, not the wide angel one. :(

**Comment by aigenseer** [comment]
Hello @rodeista, you can change the input camera by press the camera-switch-button. Every phone has a different default input camera. Did you solve the problem?

**Comment by rodeista** [comment]
Oh I see, thank you @aigenseer , I thought that this is only for front/back. And is there any way how to choose automatically one of the wide angle cameras? Because it will be much much easier for users. Now I have to choose another camera everytime, it will not remember my option :(
Thank you for superfast response:)

**Comment by aigenseer** [comment]
The idea is good. Yes, I can integrate the storage with the next update. Thanks for the tip.

**Comment by aigenseer** [comment]
Hallo @rodeista, I released a new version with the functionality today. Thanks for your idea.
