### ISSUE TITLE
error showing waiting for permissions

### ISSUE THREAD

**Issue by sunjaypb123** [aigenseer/qr-scanner-redirect#6]
pls help me in solving this issue.... its shows as waiting for permission n struck there only.....

Ref: http://shop.lavenir.in/home-scanner/

![image](https://user-images.githubusercontent.com/54257617/77221638-559c3b00-6b71-11ea-93db-87b9a249324d.png)

![image](https://user-images.githubusercontent.com/54257617/77221644-664cb100-6b71-11ea-921a-51ede1dd5f7d.png)

pls some one help

**Comment by devdatta11** [comment]
Same error any solution on this?

**Comment by aigenseer** [comment]
Hallo @sunjaypb123,

you need a https connection. The latest browser only support the camera api with a https connection.
